[theme]
primaryColor = "#005FB8"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "inter"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[server]
headless = true 
runOnSave = true
address = "localhost"
showEmailPrompt = false
enableCORS = false
enableXsrfProtection = false
