[theme]
primaryColor = "#BF0000"
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F5"
textColor = "#242024"
font = "inter"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[server]
headless = true 
runOnSave = true
address = "0.0.0.0"
showEmailPrompt = false
enableCORS = false
enableXsrfProtection = false
